import htmlmin from 'html-minifier';
const isProduction = process.env.NODE_ENV === 'production';

export default eleventyConfig => {
    eleventyConfig.addTransform("htmlmin", function(content) {
        if (
            isProduction &&
            this.page.outputPath &&
            this.page.outputPath.endsWith(".html")
        ) {
            return htmlmin.minify(content, {
                collapseBooleanAttributes: true,
                collapseWhitespace: true,
                decodeEntities: true,
                includeAutoGeneratedTags: false,
                minifyCSS: true,
                minifyJS: true,
                minifyURLs: true,
                noNewlinesBeforeTagClose: true,
                quoteCharacter: '"',
                removeComments: true,
                sortAttributes: true,
                sortClassName: true,
                useShortDoctype: true,
                processScripts: ['application/ld+json'], // minify JSON-LD scripts
            });
        }

        return content;
    });
}
