name: Trigger Netlify Build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_URL }}
